steps:
- name: node
  entrypoint: npm
  args: ['install']

- name: node
  entrypoint: npm
  args: ['run', 'build']

- name: node
  entrypoint: "bash"
  args: ['-c', 'echo REACT_APP_PRODUCTION_API_URL=https://foundation-staging-305217.uc.r.appspot.com/api/v1 > ./.env']

- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args: ["-c", "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy ./staging_app.yaml --ignore-file=.buildignore"]